/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/artwork`; params?: Router.UnknownInputParams; } | { pathname: `/capture`; params?: Router.UnknownInputParams; } | { pathname: `/cleanup`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/place`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/composePreview`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/composePreview.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/artwork`; params?: Router.UnknownOutputParams; } | { pathname: `/capture`; params?: Router.UnknownOutputParams; } | { pathname: `/cleanup`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/place`; params?: Router.UnknownOutputParams; } | { pathname: `/result`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/composePreview`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/composePreview.web`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/artwork${`?${string}` | `#${string}` | ''}` | `/capture${`?${string}` | `#${string}` | ''}` | `/cleanup${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/place${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/../utils/composePreview${`?${string}` | `#${string}` | ''}` | `/../utils/composePreview.web${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/artwork`; params?: Router.UnknownInputParams; } | { pathname: `/capture`; params?: Router.UnknownInputParams; } | { pathname: `/cleanup`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/place`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/composePreview`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/composePreview.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
ge${`?${string}` | `#${string}` | ''}` | `/../utils/webShareImage.web${`?${string}` | `#${string}` | ''}` | `/../utils/captureView${`?${string}` | `#${string}` | ''}` | `/../utils/captureView.web${`?${string}` | `#${string}` | ''}` | `/../components/WebShareButton.web${`?${string}` | `#${string}` | ''}` | `/../components/WebShareButton${`?${string}` | `#${string}` | ''}` | `/../utils/composePreview${`?${string}` | `#${string}` | ''}` | `/../utils/composePreview.web${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/artwork`; params?: Router.UnknownInputParams; } | { pathname: `/capture`; params?: Router.UnknownInputParams; } | { pathname: `/cleanup`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/place`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/webShareImage`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/webShareImage.web`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/captureView`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/captureView.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WebShareButton.web`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WebShareButton`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/composePreview`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/composePreview.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
